"""Initial migration with all tables

Revision ID: 11dc5195775d
Revises: 
Create Date: 2025-10-12 18:21:46.863533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11dc5195775d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_schedule_time',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('days_array', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('day_group_name', sa.String(length=50), nullable=False),
    sa.Column('range_text', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_schedule_time_day_group_name'), 'catalog_schedule_time', ['day_group_name'], unique=False)
    op.create_index(op.f('ix_catalog_schedule_time_is_active'), 'catalog_schedule_time', ['is_active'], unique=False)
    op.create_table('faculty',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('acronym', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculty_acronym'), 'faculty', ['acronym'], unique=True)
    op.create_index(op.f('ix_faculty_name'), 'faculty', ['name'], unique=True)
    op.create_table('user',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('profile_image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'director', 'decano', 'vicerrector', 'unauthorized', name='user_role_enum'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_is_deleted'), 'user', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('school',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('acronym', sa.String(length=20), nullable=False),
    sa.Column('fk_faculty', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['fk_faculty'], ['faculty.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_acronym'), 'school', ['acronym'], unique=False)
    op.create_index(op.f('ix_school_fk_faculty'), 'school', ['fk_faculty'], unique=False)
    op.create_index(op.f('ix_school_name'), 'school', ['name'], unique=False)
    op.create_table('user_scope',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_user', sa.UUID(), nullable=False),
    sa.Column('fk_school', sa.Integer(), nullable=True),
    sa.Column('fk_faculty', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(fk_school IS NOT NULL AND fk_faculty IS NULL) OR (fk_school IS NULL AND fk_faculty IS NOT NULL)', name='check_single_scope_assignment'),
    sa.ForeignKeyConstraint(['fk_faculty'], ['faculty.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fk_school'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fk_user'], ['user.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_scope_fk_faculty'), 'user_scope', ['fk_faculty'], unique=False)
    op.create_index(op.f('ix_user_scope_fk_school'), 'user_scope', ['fk_school'], unique=False)
    op.create_index(op.f('ix_user_scope_fk_user'), 'user_scope', ['fk_user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_scope_fk_user'), table_name='user_scope')
    op.drop_index(op.f('ix_user_scope_fk_school'), table_name='user_scope')
    op.drop_index(op.f('ix_user_scope_fk_faculty'), table_name='user_scope')
    op.drop_table('user_scope')
    op.drop_index(op.f('ix_school_name'), table_name='school')
    op.drop_index(op.f('ix_school_fk_faculty'), table_name='school')
    op.drop_index(op.f('ix_school_acronym'), table_name='school')
    op.drop_table('school')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_is_deleted'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_faculty_name'), table_name='faculty')
    op.drop_index(op.f('ix_faculty_acronym'), table_name='faculty')
    op.drop_table('faculty')
    op.drop_index(op.f('ix_catalog_schedule_time_is_active'), table_name='catalog_schedule_time')
    op.drop_index(op.f('ix_catalog_schedule_time_day_group_name'), table_name='catalog_schedule_time')
    op.drop_table('catalog_schedule_time')
    # ### end Alembic commands ###
