"""change_restored_by_id_to_string_in_recycle_bin.

Revision ID: 5aefafe9b012
Revises: c2c4b4059428
Create Date: 2025-10-15 02:16:01.154241
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5aefafe9b012"
down_revision: str | None = "c2c4b4059428"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recycle_bin",
        "restored_by_id",
        existing_type=sa.UUID(),
        type_=sa.String(length=255),
        comment="ID del usuario que restauró el registro (puede ser UUID, int, etc. como string)",
        existing_comment="UUID del usuario que restauró el registro",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recycle_bin",
        "restored_by_id",
        existing_type=sa.String(length=255),
        type_=sa.UUID(),
        comment="UUID del usuario que restauró el registro",
        existing_comment="ID del usuario que restauró el registro (puede ser UUID, int, etc. como string)",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
