"""add_soft_delete_to_faculty.

Revision ID: 7cb5fc5fcd2c
Revises: cd93d0fdb468
Create Date: 2025-10-14 19:04:06.789121
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7cb5fc5fcd2c"
down_revision: str | None = "cd93d0fdb468"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("catalog_course_course_code_key"), "catalog_course", type_="unique")
    op.add_column("faculty", sa.Column("deleted", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("faculty", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_faculty_deleted"), "faculty", ["deleted"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_faculty_deleted"), table_name="faculty")
    op.drop_column("faculty", "deleted_at")
    op.drop_column("faculty", "deleted")
    op.create_unique_constraint(
        op.f("catalog_course_course_code_key"), "catalog_course", ["course_code"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
