"""rename_is_deleted_to_deleted_in_user.

Revision ID: be33bd20bae7
Revises: d5605a7da11d
Create Date: 2025-10-14 20:55:40.918284
"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be33bd20bae7"
down_revision: str | None = "d5605a7da11d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Renombrar columna is_deleted a deleted
    op.alter_column("user", "is_deleted", new_column_name="deleted")
    # Renombrar índice
    op.drop_index(op.f("ix_user_is_deleted"), table_name="user")
    op.create_index(op.f("ix_user_deleted"), "user", ["deleted"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revertir renombre de índice
    op.drop_index(op.f("ix_user_deleted"), table_name="user")
    op.create_index(op.f("ix_user_is_deleted"), "user", ["is_deleted"], unique=False)
    # Revertir renombre de columna
    op.alter_column("user", "deleted", new_column_name="is_deleted")
    # ### end Alembic commands ###
