"""change_entity_id_to_string_in_recycle_bin.

Revision ID: c2c4b4059428
Revises: be33bd20bae7
Create Date: 2025-10-14 20:59:31.722229
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2c4b4059428"
down_revision: str | None = "be33bd20bae7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Cambiar tipo de columna entity_id de INTEGER a VARCHAR(255)
    op.alter_column(
        "recycle_bin",
        "entity_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=255),
        comment="ID del registro eliminado en su tabla original (puede ser int o UUID como string)",
        existing_comment="ID del registro eliminado en su tabla original",
        existing_nullable=False,
        postgresql_using="entity_id::text",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revertir tipo de columna entity_id de VARCHAR(255) a INTEGER
    op.alter_column(
        "recycle_bin",
        "entity_id",
        existing_type=sa.String(length=255),
        type_=sa.INTEGER(),
        comment="ID del registro eliminado en su tabla original",
        existing_comment="ID del registro eliminado en su tabla original (puede ser int o UUID como string)",
        existing_nullable=False,
        postgresql_using="entity_id::integer",
    )
    # ### end Alembic commands ###
