"""add_recycle_bin_table.

Revision ID: d5605a7da11d
Revises: 7cb5fc5fcd2c
Create Date: 2025-10-14 20:30:31.840042
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5605a7da11d"
down_revision: str | None = "7cb5fc5fcd2c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recycle_bin",
        sa.Column(
            "entity_type",
            sa.String(length=50),
            nullable=False,
            comment="Tipo de entidad: 'faculty', 'user', 'course', etc.",
        ),
        sa.Column("entity_id", sa.Integer(), nullable=False, comment="ID del registro eliminado en su tabla original"),
        sa.Column(
            "entity_display_name",
            sa.String(length=255),
            nullable=False,
            comment="Nombre legible del registro para mostrar en la UI",
        ),
        sa.Column("deleted_by_id", sa.UUID(), nullable=False, comment="UUID del usuario que eliminó el registro"),
        sa.Column(
            "deleted_by_name",
            sa.String(length=255),
            nullable=False,
            comment="Nombre del usuario que eliminó (snapshot)",
        ),
        sa.Column("reason", sa.Text(), nullable=True, comment="Razón opcional de la eliminación"),
        sa.Column(
            "restored_at", sa.DateTime(timezone=True), nullable=True, comment="Fecha y hora de restauración (si aplica)"
        ),
        sa.Column("restored_by_id", sa.UUID(), nullable=True, comment="UUID del usuario que restauró el registro"),
        sa.Column(
            "restored_by_name",
            sa.String(length=255),
            nullable=True,
            comment="Nombre del usuario que restauró (snapshot)",
        ),
        sa.Column(
            "can_restore",
            sa.Boolean(),
            nullable=False,
            comment="Indica si el registro puede ser restaurado (validación de integridad)",
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=False, comment="Fecha y hora de eliminación"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recycle_bin_deleted_at"), "recycle_bin", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_recycle_bin_deleted_by_id"), "recycle_bin", ["deleted_by_id"], unique=False)
    op.create_index(op.f("ix_recycle_bin_entity_id"), "recycle_bin", ["entity_id"], unique=False)
    op.create_index(op.f("ix_recycle_bin_entity_type"), "recycle_bin", ["entity_type"], unique=False)
    op.create_index(op.f("ix_recycle_bin_id"), "recycle_bin", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recycle_bin_id"), table_name="recycle_bin")
    op.drop_index(op.f("ix_recycle_bin_entity_type"), table_name="recycle_bin")
    op.drop_index(op.f("ix_recycle_bin_entity_id"), table_name="recycle_bin")
    op.drop_index(op.f("ix_recycle_bin_deleted_by_id"), table_name="recycle_bin")
    op.drop_index(op.f("ix_recycle_bin_deleted_at"), table_name="recycle_bin")
    op.drop_table("recycle_bin")
    # ### end Alembic commands ###
